/*
 * File: app/view/RcSteeringPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RcSteering.view.RcSteeringPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.rcsteeringpanel',

    requires: [
        'RcSteering.view.RcSteeringPanelViewModel',
        'Ext.Container',
        'Ext.field.Slider',
        'Ext.field.Number'
    ],

    viewModel: {
        type: 'rcsteeringpanel'
    },
    fullscreen: true,
    title: 'RC Steering Tester',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            userCls: 'steering-label',
            margin: 5,
            layout: 'hbox',
            items: [
                {
                    xtype: 'container',
                    width: 30,
                    html: 'L',
                    margin: '0 0 0 60'
                },
                {
                    xtype: 'container',
                    flex: 1
                },
                {
                    xtype: 'container',
                    width: 30,
                    html: 'R'
                }
            ]
        },
        {
            xtype: 'sliderfield',
            bind: '{steeringSetValue}',
            itemId: 'steeringSetPointSlider',
            name: 'steeringSlider',
            margin: '0 10 5 10',
            label: 'Steer',
            labelWidth: 50,
            value: 50,
            liveUpdate: true
        },
        {
            xtype: 'container',
            itemId: 'hbox',
            layout: 'hbox',
            items: [
                {
                    xtype: 'container',
                    itemId: 'setPointHbox',
                    userCls: 'variable-box',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'setPointActualLabel',
                            html: 'Set Point & Actual',
                            margin: 10
                        },
                        {
                            xtype: 'numberfield',
                            bind: '{steeringSetValue}',
                            itemId: 'steeringSetPointText',
                            width: 150,
                            margin: 10,
                            label: 'set point',
                            labelWidth: 70,
                            value: 50,
                            clearable: false,
                            maxValue: 100,
                            minValue: 0,
                            listeners: {
                                change: 'onSteeringSetPointTextChange'
                            }
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'steeringCurrent',
                            width: 150,
                            margin: 10,
                            label: 'current',
                            labelWidth: 70,
                            value: 0,
                            clearable: false
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'pidError',
                            width: 150,
                            margin: 10,
                            label: 'error',
                            labelWidth: 70,
                            value: 0,
                            clearable: false
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'pidHbox',
                    userCls: 'variable-box',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'pidVariablesLabel',
                            html: 'PID Variables',
                            margin: 10
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'pidConstantP',
                            width: 100,
                            margin: 10,
                            label: 'P',
                            labelWidth: 25,
                            value: 0,
                            clearable: false
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'pidConstantI',
                            width: 100,
                            margin: 10,
                            label: 'I',
                            labelWidth: 25,
                            value: 0,
                            clearable: false
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'pidConstantD',
                            width: 100,
                            margin: 10,
                            label: 'D',
                            labelWidth: 25,
                            value: 0,
                            clearable: false
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'pidOutputHbox',
                    userCls: 'variable-box',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'pidOutputsLabel',
                            html: 'PID Outputs',
                            margin: 10
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'pidIntegral',
                            margin: 10,
                            label: 'integral',
                            labelWidth: 60,
                            clearable: false
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'pidOutput',
                            margin: 10,
                            label: 'output',
                            labelWidth: 60,
                            clearable: false
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            itemId: 'debugOutputLabel',
            html: 'Debug Output',
            margin: 10
        },
        {
            xtype: 'container',
            height: 240,
            itemId: 'debugOutputContainer',
            userCls: 'debugOutputContainer',
            margin: 10,
            scrollable: 'vertical'
        }
    ],
    listeners: {
        painted: 'onFormpanelPainted'
    },

    onSteeringSetPointTextChange: function(field, newValue, oldValue, eOpts) {
        console.log("Steering Set = "+newValue);
    },

    onFormpanelPainted: function(sender, element, eOpts) {
        this.socketInit();
    },

    socketInit: function() {
        	this.socket = new WebSocket('ws://'+window.location.host+'/wsapi');

            this.appendDebugOutput("Opening Websocket");

        	this.socket.onerror = function(){
        		this.appendDebugOutput("error with websocket!");
        		return;
        	};
        	this.socket.onclose = function(){
        		this.appendDebugOutput("websocket closed!");
        		return;
        	};
        	this.socket.onmessage = this.socketReceive.bind(this);
    },

    socketSend: function(message) {
        if(!this.socket){
            console.log('Websocket not initialized');
            return false;
        }

        if(this.socket.readyState !== WebSocket.OPEN){
            console.log('Websocket not connected');
            return false;
        }

        this.socket.send(message);
    },

    socketReceive: function(message) {
        console.log('recieved message');
        console.log(message.data);

        this.appendDebugOutput('recieved message: '+message.data);

        var jsonData = JSON.parse(message.data);

        this.queryById('steeringCurrent').setValue(jsonData.steeringCurrent);
    },

    appendDebugOutput: function(message) {
        console.log(message);
        console.log(this.queryById('debugOutputContainer'));
        this.queryById('debugOutputContainer').el.dom.innerHTML += message + "<BR>\r\n";
    }

});