/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ServoTester.view.MyPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.mypanel',

    requires: [
        'ServoTester.view.MyPanelViewModel',
        'Ext.Container',
        'Ext.field.Slider',
        'Ext.field.Text'
    ],

    viewModel: {
        type: 'mypanel'
    },
    fullscreen: true,
    padding: 10,
    title: 'Servo Tester',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            layout: 'hbox',
            items: [
                {
                    xtype: 'sliderfield',
                    flex: 1,
                    bind: '{servo1}',
                    itemId: 'mysliderfield',
                    name: 'servo1',
                    label: '1',
                    labelWidth: 30,
                    value: [
                        0
                    ],
                    listeners: {
                        drag: 'onMysliderfieldDrag',
                        change: 'onMysliderfieldChange'
                    }
                },
                {
                    xtype: 'textfield',
                    bind: '{servo1}',
                    width: 80,
                    margin: '0 10 0 10',
                    clearable: false,
                    textAlign: 'center'
                }
            ]
        },
        {
            xtype: 'container',
            itemId: 'mycontainer1',
            layout: 'hbox',
            items: [
                {
                    xtype: 'sliderfield',
                    flex: 1,
                    bind: '{servo2}',
                    itemId: 'mysliderfield',
                    name: 'servo2',
                    label: '2',
                    labelWidth: 30,
                    value: [
                        0
                    ],
                    listeners: {
                        drag: 'onMysliderfieldChange1',
                        change: 'onMysliderfieldChange6'
                    }
                },
                {
                    xtype: 'textfield',
                    bind: '{servo2}',
                    width: 80,
                    margin: '0 10 0 10',
                    clearable: false,
                    textAlign: 'center'
                }
            ]
        },
        {
            xtype: 'container',
            layout: 'hbox',
            items: [
                {
                    xtype: 'sliderfield',
                    flex: 1,
                    bind: '{servo3}',
                    itemId: 'mysliderfield',
                    name: 'servo3',
                    label: '3',
                    labelWidth: 30,
                    value: [
                        0
                    ],
                    listeners: {
                        drag: 'onMysliderfieldChange2',
                        change: 'onMysliderfieldChange7'
                    }
                },
                {
                    xtype: 'textfield',
                    bind: '{servo3}',
                    width: 80,
                    margin: '0 10 0 10',
                    clearable: false,
                    textAlign: 'center'
                }
            ]
        },
        {
            xtype: 'container',
            layout: 'hbox',
            items: [
                {
                    xtype: 'sliderfield',
                    flex: 1,
                    bind: '{servo4}',
                    itemId: 'mysliderfield',
                    name: 'servo4',
                    label: '4',
                    labelWidth: 30,
                    value: [
                        0
                    ],
                    listeners: {
                        drag: 'onMysliderfieldChange3',
                        change: 'onMysliderfieldChange8'
                    }
                },
                {
                    xtype: 'textfield',
                    bind: '{servo4}',
                    width: 80,
                    margin: '0 10 0 10',
                    clearable: false,
                    textAlign: 'center'
                }
            ]
        },
        {
            xtype: 'container',
            layout: 'hbox',
            items: [
                {
                    xtype: 'sliderfield',
                    flex: 1,
                    bind: '{servo5}',
                    itemId: 'mysliderfield',
                    name: 'servo5',
                    label: '5',
                    labelWidth: 30,
                    value: [
                        0
                    ],
                    listeners: {
                        drag: 'onMysliderfieldChange4',
                        change: 'onMysliderfieldChange9'
                    }
                },
                {
                    xtype: 'textfield',
                    bind: '{servo5}',
                    width: 80,
                    margin: '0 10 0 10',
                    clearable: false,
                    textAlign: 'center'
                }
            ]
        },
        {
            xtype: 'container',
            itemId: 'mycontainer5',
            layout: 'hbox',
            items: [
                {
                    xtype: 'sliderfield',
                    flex: 1,
                    bind: '{servo6}',
                    itemId: 'mysliderfield',
                    name: 'servo6',
                    label: '6',
                    labelWidth: 30,
                    value: [
                        0
                    ],
                    listeners: {
                        drag: 'onMysliderfieldChange5',
                        change: 'onMysliderfieldChange10'
                    }
                },
                {
                    xtype: 'textfield',
                    bind: '{servo6}',
                    width: 80,
                    margin: '0 10 0 10',
                    clearable: false,
                    textAlign: 'center'
                }
            ]
        }
    ],

    onMysliderfieldDrag: function(sliderfield, sl, thumb, e, eOpts) {
        this.fieldChange(sliderfield.name,e[0]);
    },

    onMysliderfieldChange: function(me, newValue, oldValue, eOpts) {
         this.fieldChange(me.name, newValue);
    },

    onMysliderfieldChange1: function(sliderfield, sl, thumb, e, eOpts) {
        this.fieldChange(sliderfield.name,e[0]);
    },

    onMysliderfieldChange6: function(me, newValue, oldValue, eOpts) {
         this.fieldChange(me.name, newValue);
    },

    onMysliderfieldChange2: function(sliderfield, sl, thumb, e, eOpts) {
        this.fieldChange(sliderfield.name,e[0]);
    },

    onMysliderfieldChange7: function(me, newValue, oldValue, eOpts) {
         this.fieldChange(me.name, newValue);
    },

    onMysliderfieldChange3: function(sliderfield, sl, thumb, e, eOpts) {
        this.fieldChange(sliderfield.name,e[0]);
    },

    onMysliderfieldChange8: function(me, newValue, oldValue, eOpts) {
         this.fieldChange(me.name, newValue);
    },

    onMysliderfieldChange4: function(sliderfield, sl, thumb, e, eOpts) {
        this.fieldChange(sliderfield.name,e[0]);
    },

    onMysliderfieldChange9: function(me, newValue, oldValue, eOpts) {
         this.fieldChange(me.name, newValue);
    },

    onMysliderfieldChange5: function(sliderfield, sl, thumb, e, eOpts) {
        this.fieldChange(sliderfield.name,e[0]);
    },

    onMysliderfieldChange10: function(me, newValue, oldValue, eOpts) {
         this.fieldChange(me.name, newValue);
    },

    fieldChange: function(name,value) {
        console.log(name+' = '+value);

        if(this.activeRequest){
            Ext.Ajax.abort(this.activeRequest);
        }

        this.activeRequest = AERP.Ajax.request({
            url: '/updateServo',
            params:{
                servo: name,
                value: value
            },
            success:function(response){
                this.activeRequest = false;
            },
            failure:function(){

            },
            scope:this
        });

    }

});